name: resumeflow
description: "An app to create resumes and cover letters with ease."
publish_to: none

version: 0.0.0-alpha

environment:
  sdk: ^3.6.0

dependencies:
 # Flutter SDK
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Core Packages
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  go_router: ^14.6.2
  universal_io: ^2.2.2 # Provides web with the Platform API
  window_manager: ^0.4.3 # Provides an API that sets the window constraints
  shared_preferences: ^2.3.5
  http: ^1.2.2
  dio: ^5.7.0
  # State Mangement
  provider: ^6.1.2
  # UI Packages
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.16
  # Firebase
  firebase_core: ^3.9.0

dev_dependencies:
  # Flutter SDK
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # Utilties
  flutter_launcher_icons: ^0.14.2
  # Testing
  test: ^1.25.8
  mockito: ^5.4.5
  # Builders and Generators
  build_runner: ^2.4.14
  go_router_builder: ^2.7.2
  json_serializable: ^6.9.2
  json_annotation: ^4.9.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/trademark_images/

