// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuTbIvJErpfw63YZ_epeytZGivjfkN2wo',
    appId: '1:525613075966:web:478c453e7541b1c60684af',
    messagingSenderId: '525613075966',
    projectId: 'resumeflow-1b9fe',
    authDomain: 'resumeflow-1b9fe.firebaseapp.com',
    storageBucket: 'resumeflow-1b9fe.firebasestorage.app',
    measurementId: 'G-64V6P2Q536',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ8GaWaidQkzYxwjRe9HeAPnaCc6hToVs',
    appId: '1:525613075966:android:5b99e7b83fe979eb0684af',
    messagingSenderId: '525613075966',
    projectId: 'resumeflow-1b9fe',
    storageBucket: 'resumeflow-1b9fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuTbIvJErpfw63YZ_epeytZGivjfkN2wo',
    appId: '1:525613075966:web:54800b1d246212b60684af',
    messagingSenderId: '525613075966',
    projectId: 'resumeflow-1b9fe',
    authDomain: 'resumeflow-1b9fe.firebaseapp.com',
    storageBucket: 'resumeflow-1b9fe.firebasestorage.app',
    measurementId: 'G-J9LWQW7LV1',
  );
}
